version: '3'

services:
  database:
    image: mysql:5.7
    restart: always
    environment:
      MYSQL_DATABASE: 'instant'
      MYSQL_ROOT_PASSWORD: 'root'
      MYSQL_USER: 'instant'
      MYSQL_PASSWORD: 'instant'
      TZ: Etc/UTC
    command: mysqld --sql_mode=""
    ports:
      - 3306:3306
    expose:
      - 3306
    volumes:
      - ./mysql-dump:/docker-entrypoint-initdb.d
  rabbitmq:
    image: rabbitmq:3-management-alpine
    hostname: my-rabbit
    volumes:
      - ./rabbitmq/etc/definitions.json:/etc/rabbitmq/definitions.json
      - ./rabbitmq/etc/rabbitmq.conf:/etc/rabbitmq/rabbitmq.conf
      - ./rabbitmq/data:/var/lib/rabbitmq/mnesia/rabbit@my-rabbit
      - ./rabbitmq/logs:/var/log/rabbitmq/log
    ports:
      - 5672:5672
      - 15672:15672
    expose:
      - 5672