version: '2.1'
orbs:
  node: circleci/node@4.2.0
jobs:
  install-node:
    docker:
      - image: 'cimg/base:stable'
    steps:
      - checkout
      - node/install:
          install-yarn: true
      - run: node --version
      - run: yarn test
workflows:
  test-app-istants-pic:
    jobs:
      - install-node