version: '2.1'
orbs:
  node: circleci/node@4.2.0
jobs:
  test-app:
    machine:
      image: ubuntu-2004:202010-01
    steps:
      - checkout
      - setup_remote_docker:
          version: 19.03.13
      - node/install:
          install-yarn: true
      - run: yarn install
      - run: yarn test
workflows:
  test-app-istants-pic:
    jobs:
      - test-app