version: '2.1'
orbs:
  node: circleci/node@4.2.0
jobs:
  test-app:
    steps:
      - checkout
      - node/install:
          install-yarn: true
      - run: yarn install
      - run: yarn test
    executor:
    machine:
      image: ubuntu-2004:202010-01
workflows:
  test-app-istants-pic:
    jobs:
      - test-app